package com.jshop.entity;
// Generated 2011-12-21 20:50:55 by Hibernate Tools 3.2.1.GA



/**
 * GlobalParamM generated by hbm2java
 */
public class GlobalParamM  implements java.io.Serializable {


     private String gkey;
     private String gvalue;

    public GlobalParamM() {
    }

    public GlobalParamM(String gkey, String gvalue) {
       this.gkey = gkey;
       this.gvalue = gvalue;
    }
   
    public String getGkey() {
        return this.gkey;
    }
    
    public void setGkey(String gkey) {
        this.gkey = gkey;
    }
    public String getGvalue() {
        return this.gvalue;
    }
    
    public void setGvalue(String gvalue) {
        this.gvalue = gvalue;
    }




}


