del ..\..\cache\init\*.*js
del ..\..\cache\main\*.*js
del ..\..\cache\mainMobile\*.*js
del ..\..\cache\mainBiz\*.*js
del ..\..\cache\mainStore\*.*js
del ..\..\cache\mainSub\*.*js
del ..\..\cache\mainGroup\*.*js
del ..\..\cache\mainPage\*.*js
del ..\..\cache\mainView\*.*js
del ..\..\cache\mainChat\*.*js
del ..\..\cache\portal\*.*js
del ..\..\cache\portalMobile\*.*js
del ..\..\cache\portalBiz\*.*js
del ..\..\cache\portalSub\*.*js
del ..\..\cache\portalGroup\*.*js
del ..\..\cache\portalPage\*.*js
del ..\..\cache\portalStore\*.*js
del ..\..\cache\portalView\*.*js
del ..\..\cache\portalChat\*.*js
del ..\..\cache\lazyLoading\*.*js