INSERT INTO `tb_second_category` ('second_id','name_en','name_cn','first_id') VALUES ('1', 'Hairdressing', '美发', '1');
INSERT INTO `tb_second_category` ('second_id','name_en','name_cn','first_id') VALUES ('2', 'SPA', '美容美体', '1');
INSERT INTO `tb_second_category` ('second_id','name_en','name_cn','first_id') VALUES ('3', 'Slimming', '瘦身减肥', '1');
INSERT INTO `tb_second_category` ('second_id','name_en','name_cn','first_id') VALUES ('4', 'Nail Spa', '美甲', '1');


INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('5', 'Auction', '拍卖', '2');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('6', 'Car', '汽车', '2');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('7', 'Investment venture center', '投资创业中心', '2');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('8', 'Education Products', '教育产品', '2');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('9', 'Software&Network', '网络&软件', '2');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('10', 'Advertising ', '广告', '2');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('11', 'Insurance Company', '保险公司', '2');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('12', 'Securities company', '证券公司', '2');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('13', 'Parents-Children ', '托儿所', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('14', 'Kindergarden', '幼儿园', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('15', 'Primary School ', '小学', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('16', 'Middle School', '中学', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('17', 'Primary School and Middle School', '中小学', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('18', 'Language school', '语言学校', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('19', 'International school', '国际学校', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('20', 'University', '大学', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('21', 'Secondary specialized school', '中等专科学校', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('22', 'Vocational and Technical College', '职业技术学校', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('23', 'Education Training School', '教育培训学校', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('24', 'Senior Citizen University', '老年大学', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('25', 'Adult education', '成人教育学校', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('26', 'Vocational Training School', '职业培训学校', '3');

INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('29', 'Clothing Training School', '服装培训', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('30', 'Computer Training School', '电脑培训', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('31', 'Management Training School', '管理培训', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('32', 'Beauty Training School', '美容美发培训', '3');
INSERT INTO `tb_second_category` VALUES ('second_id','name_en','name_cn','first_id') ('33', 'Accounting Training School', '会计培训', '3');

INSERT INTO `tb_second_category` VALUES ('34', 'Accounting Correspondence School', '会计函授学校', '3');
INSERT INTO `tb_second_category` VALUES ('35', 'Health School', '卫生进修学校', '3');
INSERT INTO `tb_second_category` VALUES ('36', 'Special Education', '特殊教育学校', '3');
INSERT INTO `tb_second_category` VALUES ('37', 'Sports School', '体育运动学校', '3');
INSERT INTO `tb_second_category` VALUES ('38', 'Art Training School', '艺术培训学校', '3');
INSERT INTO `tb_second_category` VALUES ('39', 'Family education', '家教', '3');
INSERT INTO `tb_second_category` VALUES ('40', 'Association', '协会', '4');
INSERT INTO `tb_second_category` VALUES ('41', 'Government', '政府机关', '4');
INSERT INTO `tb_second_category` VALUES ('42', 'Police', '公安&警察', '4');
INSERT INTO `tb_second_category` VALUES ('43', 'Subdistrict', '街道办事处', '4');
INSERT INTO `tb_second_category` VALUES ('44', 'Finance', '财政局', '4');
INSERT INTO `tb_second_category` VALUES ('45', 'Tax', '税务局', '4');
INSERT INTO `tb_second_category` VALUES ('46', 'Court', '法院', '4');
INSERT INTO `tb_second_category` VALUES ('47', 'Procuratorate', '检察院', '4');
INSERT INTO `tb_second_category` VALUES ('48', 'Entry and exit inspection and quarantine', '出入境检验检疫局', '4');
INSERT INTO `tb_second_category` VALUES ('49', 'Blood Donation', '献血办公室', '4');
INSERT INTO `tb_second_category` VALUES ('50', 'Information center', '信息中心', '4');
INSERT INTO `tb_second_category` VALUES ('51', 'Productivity promotion center', '生产力促进中心', '4');
INSERT INTO `tb_second_category` VALUES ('52', 'Bidding center', '投标中心', '4');
INSERT INTO `tb_second_category` VALUES ('53', 'Family Planning', '计划生育', '4');
INSERT INTO `tb_second_category` VALUES ('54', 'Research society', '研究会', '4');
INSERT INTO `tb_second_category` VALUES ('55', 'Office', '办公室', '4');
INSERT INTO `tb_second_category` VALUES ('56', 'Management center', '管理中心', '4');
INSERT INTO `tb_second_category` VALUES ('57', 'Federation', '联合会', '4');
INSERT INTO `tb_second_category` VALUES ('58', 'Committees', '委员会', '4');
INSERT INTO `tb_second_category` VALUES ('59', 'Village committee', '村民委员会', '4');
INSERT INTO `tb_second_category` VALUES ('60', 'Neighborhood Committee', '居民委员会', '4');
INSERT INTO `tb_second_category` VALUES ('61', 'Telecom', '电信局', '4');
INSERT INTO `tb_second_category` VALUES ('62', 'Post Office', '邮政局', '4');
INSERT INTO `tb_second_category` VALUES ('63', '2 Star', '2星级', '5');
INSERT INTO `tb_second_category` VALUES ('64', '3 Star', '3星级', '5');
INSERT INTO `tb_second_category` VALUES ('65', '4 Star', '4星级', '5');
INSERT INTO `tb_second_category` VALUES ('66', '5 Star', '5星级', '5');
INSERT INTO `tb_second_category` VALUES ('67', 'Inns', '连锁酒店', '5');
INSERT INTO `tb_second_category` VALUES ('68', 'Hostels', '旅馆', '5');
INSERT INTO `tb_second_category` VALUES ('69', 'Resorts', '度假村&山庄', '5');
INSERT INTO `tb_second_category` VALUES ('70', 'Residential quarters', '住宅小区', '5');
INSERT INTO `tb_second_category` VALUES ('71', 'Apartments', '公寓', '5');
INSERT INTO `tb_second_category` VALUES ('72', 'Chinese Medicine', '中医', '6');
INSERT INTO `tb_second_category` VALUES ('73', 'General Hospitals', '综合医院', '6');
INSERT INTO `tb_second_category` VALUES ('74', 'Special Hospitals', '专科医院', '6');
INSERT INTO `tb_second_category` VALUES ('75', 'Plastic Surgery Hospitals', '整形外科医院', '6');
INSERT INTO `tb_second_category` VALUES ('76', 'Emergency Center', '急救中心', '6');
INSERT INTO `tb_second_category` VALUES ('77', 'Dental Clinics', '口腔诊所', '6');
INSERT INTO `tb_second_category` VALUES ('78', 'Clinics', '卫生院', '6');
INSERT INTO `tb_second_category` VALUES ('79', 'Vets', '宠物医院', '6');
INSERT INTO `tb_second_category` VALUES ('80', 'Maternal and Child Health Hospital', '妇幼保健院', '6');
INSERT INTO `tb_second_category` VALUES ('81', 'Rehabilitation center', '康复中心', '6');
INSERT INTO `tb_second_category` VALUES ('82', 'Mental Hospitals', '精神病医院', '6');
INSERT INTO `tb_second_category` VALUES ('83', 'Orthopaedic Centre', '矫形中心', '6');
INSERT INTO `tb_second_category` VALUES ('84', 'CDC', '疾病预防控制中心', '6');
INSERT INTO `tb_second_category` VALUES ('85', 'Dispensary', '防治站', '6');
INSERT INTO `tb_second_category` VALUES ('86', 'Pharmacy', '大药房', '6');
INSERT INTO `tb_second_category` VALUES ('87', 'Welfare Centre', '福利院', '6');
INSERT INTO `tb_second_category` VALUES ('88', 'Live Music Bar', '现场音乐酒吧', '7');
INSERT INTO `tb_second_category` VALUES ('89', 'Bars', '酒吧', '7');
INSERT INTO `tb_second_category` VALUES ('90', 'KTV', 'KTV', '7');
INSERT INTO `tb_second_category` VALUES ('91', 'Club', '酒吧会所', '7');
INSERT INTO `tb_second_category` VALUES ('92', 'Nightclubs', '夜总会', '7');
INSERT INTO `tb_second_category` VALUES ('93', 'Buffet', '自助餐', '8');
INSERT INTO `tb_second_category` VALUES ('94', 'BBQ', '烧烤', '8');
INSERT INTO `tb_second_category` VALUES ('95', 'Fastfood', '快餐', '8');
INSERT INTO `tb_second_category` VALUES ('96', 'Chain shop', '连锁店', '8');
INSERT INTO `tb_second_category` VALUES ('97', 'Seafood', '海鲜', '8');
INSERT INTO `tb_second_category` VALUES ('98', 'Ningbonese', '宁波菜', '8');
INSERT INTO `tb_second_category` VALUES ('99', 'Szechuan&Hunan', '川湘菜', '8');
INSERT INTO `tb_second_category` VALUES ('100', 'Zhejiang', '江浙菜', '8');
INSERT INTO `tb_second_category` VALUES ('101', 'Dongbei', '东北菜', '8');
INSERT INTO `tb_second_category` VALUES ('102', 'Creative Dishes', '创意菜', '8');
INSERT INTO `tb_second_category` VALUES ('103', 'Cantonese', '粤菜', '8');
INSERT INTO `tb_second_category` VALUES ('104', 'Hong Kong', '港式', '8');
INSERT INTO `tb_second_category` VALUES ('105', 'Hot pot', '火锅', '8');
INSERT INTO `tb_second_category` VALUES ('106', 'Chicken Pot', '鸡煲', '8');
INSERT INTO `tb_second_category` VALUES ('107', 'Snacks', '小吃', '8');
INSERT INTO `tb_second_category` VALUES ('108', 'Porridge', '粥', '8');
INSERT INTO `tb_second_category` VALUES ('109', 'Yunnan', '云南', '8');
INSERT INTO `tb_second_category` VALUES ('110', 'Lanzhou', '兰州', '8');
INSERT INTO `tb_second_category` VALUES ('111', 'Xinjiang', '新疆', '8');
INSERT INTO `tb_second_category` VALUES ('112', 'Vegetarian', '素食餐厅', '8');
INSERT INTO `tb_second_category` VALUES ('113', 'Food City', '美食城', '8');
INSERT INTO `tb_second_category` VALUES ('114', 'Western Food', '西餐', '8');
INSERT INTO `tb_second_category` VALUES ('115', 'Pizza', '披萨', '8');
INSERT INTO `tb_second_category` VALUES ('116', 'Steak', '牛排', '8');
INSERT INTO `tb_second_category` VALUES ('117', 'Teooanyaki', '铁板烧', '8');
INSERT INTO `tb_second_category` VALUES ('118', 'Thai', '泰国菜', '8');
INSERT INTO `tb_second_category` VALUES ('119', 'Southeast Asia', '东南亚菜', '8');
INSERT INTO `tb_second_category` VALUES ('120', 'Indian', '印度菜', '8');
INSERT INTO `tb_second_category` VALUES ('121', 'Italian ', '意大利', '8');
INSERT INTO `tb_second_category` VALUES ('122', 'Japanese', '日本料理', '8');
INSERT INTO `tb_second_category` VALUES ('123', 'Korean', '韩式料理', '8');
INSERT INTO `tb_second_category` VALUES ('124', 'Desserts', '甜品', '8');
INSERT INTO `tb_second_category` VALUES ('125', 'Drinks', '奶茶', '8');
INSERT INTO `tb_second_category` VALUES ('126', 'Bakeries', '烘培坊', '8');
INSERT INTO `tb_second_category` VALUES ('127', 'Teahouse', '茶馆', '8');
INSERT INTO `tb_second_category` VALUES ('128', 'Coffee', '咖啡店', '8');
INSERT INTO `tb_second_category` VALUES ('129', 'Others', '其他', '8');
INSERT INTO `tb_second_category` VALUES ('130', 'Service Center', '服务中心', '9');
INSERT INTO `tb_second_category` VALUES ('131', 'Mobile', '手机', '9');
INSERT INTO `tb_second_category` VALUES ('132', 'Laundry', '洗衣店', '9');
INSERT INTO `tb_second_category` VALUES ('133', 'Transit System Farecard', '公交充值', '9');
INSERT INTO `tb_second_category` VALUES ('134', 'China Mobile ', '中国移动', '9');
INSERT INTO `tb_second_category` VALUES ('135', 'China unicom', '中国联通', '9');
INSERT INTO `tb_second_category` VALUES ('136', 'Tickets', '售票处', '9');
INSERT INTO `tb_second_category` VALUES ('137', 'Funeral home', '殡仪馆', '9');
INSERT INTO `tb_second_category` VALUES ('138', 'Social insurance', '社会保险', '9');
INSERT INTO `tb_second_category` VALUES ('139', 'Medical management center', '医疗管理中心', '9');
INSERT INTO `tb_second_category` VALUES ('140', 'Salvation management station', '救助管理站', '9');
INSERT INTO `tb_second_category` VALUES ('141', 'Labor market', '人才市场', '9');
INSERT INTO `tb_second_category` VALUES ('142', 'Cemetery ', '墓园', '9');
INSERT INTO `tb_second_category` VALUES ('143', 'Car Rental', '汽车租赁', '9');
INSERT INTO `tb_second_category` VALUES ('144', 'Law firm', '律师事务所', '9');
INSERT INTO `tb_second_category` VALUES ('145', 'Accounting Firm', '会计师事务所', '9');
INSERT INTO `tb_second_category` VALUES ('146', 'Moving Services', '搬家服务', '9');
INSERT INTO `tb_second_category` VALUES ('147', 'Household Services', '家政服务', '9');
INSERT INTO `tb_second_category` VALUES ('148', 'Living Services', '生活服务', '9');
INSERT INTO `tb_second_category` VALUES ('149', 'Express delivery company', '快递', '9');
INSERT INTO `tb_second_category` VALUES ('150', 'Gas station', '加油站', '9');
INSERT INTO `tb_second_category` VALUES ('151', 'Travel Service', '旅游服务', '9');
INSERT INTO `tb_second_category` VALUES ('152', 'Photography', '摄影', '9');
INSERT INTO `tb_second_category` VALUES ('153', 'Wedding etiquette', '婚庆', '9');
INSERT INTO `tb_second_category` VALUES ('154', 'Recycling station', '回收站', '9');
INSERT INTO `tb_second_category` VALUES ('155', 'Intermediary', '中介', '9');
INSERT INTO `tb_second_category` VALUES ('156', 'Biological products', '生物制品', '10');
INSERT INTO `tb_second_category` VALUES ('157', 'Health care products', '保健食品', '10');
INSERT INTO `tb_second_category` VALUES ('158', 'Medical equipment', '医疗设备', '10');
INSERT INTO `tb_second_category` VALUES ('159', 'Supermarket', '超市', '10');
INSERT INTO `tb_second_category` VALUES ('160', 'Department store ', '百货商店', '10');
INSERT INTO `tb_second_category` VALUES ('161', 'Plaza', '购物中心', '10');
INSERT INTO `tb_second_category` VALUES ('162', 'Fashion', '服饰', '10');
INSERT INTO `tb_second_category` VALUES ('163', 'Electrical appliance', '电器', '10');
INSERT INTO `tb_second_category` VALUES ('164', 'Digital products', '数码产品', '10');
INSERT INTO `tb_second_category` VALUES ('165', 'Furniture', '家居', '10');
INSERT INTO `tb_second_category` VALUES ('166', 'Hardware&Material&Fittings', '五金配件', '10');
INSERT INTO `tb_second_category` VALUES ('167', 'Integrated market', '综合市场', '10');
INSERT INTO `tb_second_category` VALUES ('168', 'Pet&Plant market', '花鸟市场', '10');
INSERT INTO `tb_second_category` VALUES ('169', 'Malls', '商城', '10');
INSERT INTO `tb_second_category` VALUES ('170', 'Fishing gear', '渔具', '10');
INSERT INTO `tb_second_category` VALUES ('171', 'Others', '其他', '10');
INSERT INTO `tb_second_category` VALUES ('172', 'Books', '书店', '10');
INSERT INTO `tb_second_category` VALUES ('173', 'CD', 'VCD&DVD shop', '0');
INSERT INTO `tb_second_category` VALUES ('174', 'Mobile', '手机', '10');
INSERT INTO `tb_second_category` VALUES ('175', 'Watches', '钟表', '10');
INSERT INTO `tb_second_category` VALUES ('176', 'Wine shops', '酒庄', '10');
INSERT INTO `tb_second_category` VALUES ('177', 'Convenience store', '便利店', '10');
INSERT INTO `tb_second_category` VALUES ('178', 'Sports Supplies', '文体用品', '10');
INSERT INTO `tb_second_category` VALUES ('179', 'Leisure products', '休闲用品', '10');
INSERT INTO `tb_second_category` VALUES ('180', 'Fitness equipment', '运动器材', '10');
INSERT INTO `tb_second_category` VALUES ('181', 'Bicycle', '自行车', '10');
INSERT INTO `tb_second_category` VALUES ('182', 'Electric vehicle', '电动车', '10');
INSERT INTO `tb_second_category` VALUES ('183', 'Toy', '玩具', '10');
INSERT INTO `tb_second_category` VALUES ('184', 'Musical instruments', '乐器', '10');
INSERT INTO `tb_second_category` VALUES ('185', 'Kitchen equipment and supplies', '厨具', '10');
INSERT INTO `tb_second_category` VALUES ('186', 'Pet', '宠物用品', '10');
INSERT INTO `tb_second_category` VALUES ('187', 'Flowers&Gifts', '鲜花礼品', '10');
INSERT INTO `tb_second_category` VALUES ('188', 'Glasses', '眼镜', '10');
INSERT INTO `tb_second_category` VALUES ('189', 'Jewelries', '珠宝', '10');
INSERT INTO `tb_second_category` VALUES ('190', 'Yoga', '瑜伽', '11');
INSERT INTO `tb_second_category` VALUES ('191', 'Gym', '健身房', '11');
INSERT INTO `tb_second_category` VALUES ('192', 'Fishing', '钓鱼', '11');
INSERT INTO `tb_second_category` VALUES ('193', 'Yacht', '游艇', '11');
INSERT INTO `tb_second_category` VALUES ('194', 'Tai chi ', '太极拳', '11');
INSERT INTO `tb_second_category` VALUES ('195', 'Stadium', '体育馆', '11');
INSERT INTO `tb_second_category` VALUES ('196', 'Basketball', '篮球', '11');
INSERT INTO `tb_second_category` VALUES ('197', 'Golf', '高尔夫', '11');
INSERT INTO `tb_second_category` VALUES ('198', 'Ski', '滑雪', '11');
INSERT INTO `tb_second_category` VALUES ('199', 'Shooting ', '射击', '11');
INSERT INTO `tb_second_category` VALUES ('200', 'Squash', '壁球', '11');
INSERT INTO `tb_second_category` VALUES ('201', 'Swimming', '游泳', '11');
INSERT INTO `tb_second_category` VALUES ('202', 'Taekwondo ', '跆拳道', '11');
INSERT INTO `tb_second_category` VALUES ('203', 'Tennis', '网球', '11');
INSERT INTO `tb_second_category` VALUES ('204', 'Lakes', '湖', '11');
INSERT INTO `tb_second_category` VALUES ('205', 'Parks', '公园', '11');
INSERT INTO `tb_second_category` VALUES ('206', 'Kids Fun', '游乐园', '11');
INSERT INTO `tb_second_category` VALUES ('207', 'Square', '广场', '11');
INSERT INTO `tb_second_category` VALUES ('208', 'Theatre', '剧院', '11');
INSERT INTO `tb_second_category` VALUES ('209', 'Ancient town', '古镇', '11');
INSERT INTO `tb_second_category` VALUES ('210', 'Exhibition Center', '会展中心', '11');
INSERT INTO `tb_second_category` VALUES ('211', 'Paiting', '画画', '11');
INSERT INTO `tb_second_category` VALUES ('212', 'Music hall', '音乐厅', '11');
INSERT INTO `tb_second_category` VALUES ('213', 'Museums', '博物馆', '11');
INSERT INTO `tb_second_category` VALUES ('214', 'Church', '教堂', '11');
INSERT INTO `tb_second_category` VALUES ('215', 'Drift', '漂流', '11');
INSERT INTO `tb_second_category` VALUES ('216', 'Fishing', '渔村', '11');
INSERT INTO `tb_second_category` VALUES ('217', 'Tourist Attractions', '旅游景区', '11');
INSERT INTO `tb_second_category` VALUES ('218', 'Temples', '寺庙', '11');
INSERT INTO `tb_second_category` VALUES ('219', 'Cinema', '电影院', '11');
INSERT INTO `tb_second_category` VALUES ('220', 'Baths', '浴场', '11');
INSERT INTO `tb_second_category` VALUES ('221', 'Massage', '推拿', '11');
INSERT INTO `tb_second_category` VALUES ('222', 'Lavipeditum', '足道', '11');
INSERT INTO `tb_second_category` VALUES ('223', 'Dancing Hall', '舞厅', '11');
INSERT INTO `tb_second_category` VALUES ('224', 'Internet Bar', '网吧', '11');
INSERT INTO `tb_second_category` VALUES ('225', 'Billiards Club', '台球会所', '11');
INSERT INTO `tb_second_category` VALUES ('226', 'Board Game', '桌游馆', '11');
INSERT INTO `tb_second_category` VALUES ('227', 'Chess Room', '棋牌室', '11');
INSERT INTO `tb_second_category` VALUES ('228', 'Airport', '机场', '12');
INSERT INTO `tb_second_category` VALUES ('229', 'Bus ', '汽车站', '12');
INSERT INTO `tb_second_category` VALUES ('230', 'Ship', '码头', '12');
INSERT INTO `tb_second_category` VALUES ('231', 'Train ', '火车站', '12');
INSERT INTO `tb_second_category` VALUES ('232', 'Office ', '写字楼', '13');
INSERT INTO `tb_second_category` VALUES ('233', 'SCB', '渣打银行', '14');
INSERT INTO `tb_second_category` VALUES ('234', 'HSB', '恒生银行', '14');
INSERT INTO `tb_second_category` VALUES ('235', 'HSBC', '汇丰银行', '14');
INSERT INTO `tb_second_category` VALUES ('236', 'BINB', '宁波国际银行', '14');
INSERT INTO `tb_second_category` VALUES ('237', 'Bank of Shanghai', '上海银行', '14');
INSERT INTO `tb_second_category` VALUES ('238', 'ABC', '农业银行', '14');
INSERT INTO `tb_second_category` VALUES ('239', 'BOC', '中国银行', '14');
INSERT INTO `tb_second_category` VALUES ('240', 'BOCOM', '交通银行', '14');
INSERT INTO `tb_second_category` VALUES ('241', 'CBC', '建设银行', '14');
INSERT INTO `tb_second_category` VALUES ('242', 'CMB', '招商银行', '14');
INSERT INTO `tb_second_category` VALUES ('243', 'ICBC', '工商银行', '14');
INSERT INTO `tb_second_category` VALUES ('244', 'PBOC', '人民银行', '14');
INSERT INTO `tb_second_category` VALUES ('245', 'NBCB', '宁波银行', '14');
INSERT INTO `tb_second_category` VALUES ('246', 'SPDB', '浦发银行', '14');
INSERT INTO `tb_second_category` VALUES ('247', 'SDB', '深圳发展银行', '14');
INSERT INTO `tb_second_category` VALUES ('248', 'Yinzhou Bank', '鄞州银行', '14');
INSERT INTO `tb_second_category` VALUES ('249', 'CMBC', '民生银行', '14');
INSERT INTO `tb_second_category` VALUES ('250', 'CZB', '浙商银行', '14');
INSERT INTO `tb_second_category` VALUES ('251', 'BSB', '包商银行', '14');
INSERT INTO `tb_second_category` VALUES ('252', 'Wenzhou Bank', '温州银行', '14');
INSERT INTO `tb_second_category` VALUES ('253', 'ZJTLCB', '浙江泰隆商业银行', '14');
INSERT INTO `tb_second_category` VALUES ('254', 'CIB', '兴业银行', '14');
INSERT INTO `tb_second_category` VALUES ('255', 'HXB', '华夏银行', '14');
INSERT INTO `tb_second_category` VALUES ('256', 'CGB', '广发银行', '14');
INSERT INTO `tb_second_category` VALUES ('257', 'CEB', '光大银行', '14');
INSERT INTO `tb_second_category` VALUES ('258', 'CITIC', '中信银行', '14');
INSERT INTO `tb_second_category` VALUES ('259', 'CPBC', '邮政储蓄', '14');
INSERT INTO `tb_second_category` VALUES ('260', 'Newspaper', '报纸', '15');