package anni.anews.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;


/**
 * NewsConfig generated by Lingo.
 *
 * @author Lingo
 * @since 2007年08月16日 下午 23时13分00秒31
 */
@Entity
@Table(name = "A_NEWS_CONFIG")
public class NewsConfig implements Serializable {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * 默认配置的id. */
    public static final long DEFAULT_CONFIG_ID = 1L;

    /** * 默认模板名称. */
    public static final String DEFAULT_TEMPLATE_NAME = "default";

    /** * id. */
    private Long id;

    /** * newsNeedAudit. */
    private Integer newsNeedAudit;

    /** * commentNeedAudit. */
    private Integer commentNeedAudit;

    /** * couldComment. */
    private Integer couldComment;

    /** * categoryStrategy. */
    private Integer categoryStrategy;

    /** * templateName. */
    private String templateName;

    /** * 构造方法. */
    public NewsConfig() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id id. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return newsNeedAudit. */
    @Column(name = "NEWS_NEED_AUDIT")
    public Integer getNewsNeedAudit() {
        return newsNeedAudit;
    }

    /** * @param newsNeedAudit newsNeedAudit. */
    public void setNewsNeedAudit(Integer newsNeedAudit) {
        this.newsNeedAudit = newsNeedAudit;
    }

    /** * @return commentNeedAudit. */
    @Column(name = "COMMENT_NEED_AUDIT")
    public Integer getCommentNeedAudit() {
        return commentNeedAudit;
    }

    /** * @param commentNeedAudit commentNeedAudit. */
    public void setCommentNeedAudit(Integer commentNeedAudit) {
        this.commentNeedAudit = commentNeedAudit;
    }

    /** * @return couldComment. */
    @Column(name = "COULD_COMMENT")
    public Integer getCouldComment() {
        return couldComment;
    }

    /** * @param couldComment couldComment. */
    public void setCouldComment(Integer couldComment) {
        this.couldComment = couldComment;
    }

    /** * @return categoryStrategy. */
    @Column(name = "CATEGORY_STRATEGY")
    public Integer getCategoryStrategy() {
        return categoryStrategy;
    }

    /** * @param categoryStrategy Integer. */
    public void setCategoryStrategy(Integer categoryStrategy) {
        this.categoryStrategy = categoryStrategy;
    }

    /** * @return templateName. */
    @Column(name = "TEMPLATE_NAME", length = 50)
    public String getTemplateName() {
        return templateName;
    }

    /** * @param templateName String. */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }
}
