	config.eventcfg = {
		deleteWf: function(){
			var self = this;
			var records = self.grid.getSelectionModel().getSelections();
			if (!JxUtil.selectone(records)) return;
			
			var record = records[0];
			var state = record.get('wf_process__process_state');
			if (state != '1') {
				JxHint.alert(jx.wf.nodel);	//'当前过程不是“定义”状态，不能删除！'
				return true;
			}

			var hdcall = function() {
				//设置请求的参数
				var params = 'funid=wf_process&keyid=' + record.get(self.define.pkcol);
				params += '&pagetype=editgrid&eventcode=delete';
				
				//重新加载数据
				var endcall = function() {
					self.grid.getStore().reload();
				}
				//发送请求
				Request.postRequest(params, endcall);
			};
			//'确定删除当前过程定义及所有相关设计信息吗？'
			Ext.Msg.confirm(jx.base.hint, jx.wf.delyes, function(btn) {
				if (btn == 'yes') hdcall();
			});
		},
	
		checkwf: function(){
			var self = this;
			var records = self.grid.getSelectionModel().getSelections();
			if (!JxUtil.selectone(records)) return;
			
			//设置请求的参数
			var params = 'funid=wf_process&keyid=' + records[0].get(self.define.pkcol);
			params += '&pagetype=editgrid&eventcode=checkwf';

			//发送请求
			Request.postRequest(params, null);
		},
		
		enablewf: function(){
			var self = this;
			var records = self.grid.getSelectionModel().getSelections();
			if (!JxUtil.selectone(records)) return;
			
			var record = records[0];
			var state = record.get('wf_process__process_state');
			if (state == '2') {
				JxHint.alert(jx.wf.dontuse);	//'当前过程已经启用，不能再启用！'
				return true;
			}

			var oldProcessId = record.get('wf_process__old_processid');
			var hdcall = function() {
				//设置请求的参数
				var params = 'funid=wf_process&keyid=' + record.get(self.define.pkcol);
				params += '&pagetype=editgrid&eventcode=enable&old_processid=' + oldProcessId;
				
				var endcall = function() {
					self.grid.getStore().reload();
				}
				//发送请求
				Request.postRequest(params, endcall);
			};
			//'确定启用当前过程定义吗？'
			Ext.Msg.confirm(jx.base.hint, jx.wf.useyes, function(btn) {
				if (btn == 'yes') hdcall();
			});
		},
		
		disablewf: function(){
			var self = this;
			var records = self.grid.getSelectionModel().getSelections();
			if (!JxUtil.selectone(records)) return;
			
			var record = records[0];
			var state = record.get('wf_process__process_state');
			if (state != '2') {
				JxHint.alert(jx.wf.nodis);	//'当前过程没有启用，不能禁用！'
				return true;
			}

			var hdcall = function() {
				//设置请求的参数
				var params = 'funid=wf_process&keyid=' + record.get(self.define.pkcol);
				params += '&pagetype=editgrid&eventcode=disablewf';
				
				var endcall = function() {
					record.set('wf_process__process_state', '3');
					record.commit();
				}
				//发送请求
				Request.postRequest(params, endcall);
			};
			//'禁用后过程不能再使用，确定禁用吗？'
			Ext.Msg.confirm(jx.base.hint, jx.wf.disyes, function(btn) {
				if (btn == 'yes') hdcall();
			});
		},
		
		newversion: function(){
			var self = this;
			var records = self.grid.getSelectionModel().getSelections();
			if (!JxUtil.selectone(records)) return;
			
			var record = records[0];
			var state = record.get('wf_process__process_state');
			if (state != '2') {
				JxHint.alert(jx.wf.dontnew);	//'当前过程没有启用，不能创建新版本！'
				return true;
			}

			var hdcall = function() {
				//设置请求的参数
				var params = 'funid=wf_process&keyid=' + record.get(self.define.pkcol);
				params += '&pagetype=editgrid&eventcode=newversion';
				//重新加载数据
				var endcall = function() {
					self.grid.getStore().reload();
				}
				//发送请求
				Request.postRequest(params, endcall);
			};
			//'确定创建新版流程定义吗？'
			Ext.Msg.confirm(jx.base.hint, jx.wf.newyes, function(btn) {
				if (btn == 'yes') hdcall();
			});
		},
		
		copywf: function(){
			var self = this;
			var records = self.grid.getSelectionModel().getSelections();
			if (!JxUtil.selectone(records)) return;

			var hdcall = function() {
				//设置请求的参数
				var params = 'funid=wf_process&keyid=' + records[0].get(self.define.pkcol);
				params += '&pagetype=editgrid&eventcode=copywf';
				//重新加载数据
				var endcall = function() {
					self.grid.getStore().reload();
				}
				//发送请求
				Request.postRequest(params, endcall);
			};
			//'确定复制流程定义吗？'
			Ext.Msg.confirm(jx.base.hint, jx.wf.copyes, function(btn) {
				if (btn == 'yes') hdcall();
			});
		}
	};
	
	config.initpage = function(gridNode){
		var grid = gridNode.page;
		//表格编辑前事件 
		grid.on('beforeedit', function(event) {
			var r = event.record;
			var state = r.get('wf_process__process_state');
			//非定义状态记录不能修改
			if (state != '1') {
				return false;
			}
			
			return true;
		});
	};