//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.23 at 02:16:13 PM PDT 
//


package org.light.portal.layout.config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}column"/>
 *         &lt;element ref="{}row"/>
 *         &lt;element ref="{}notCloseable" minOccurs="0"/>
 *         &lt;element ref="{}noEditMode" minOccurs="0"/>
 *         &lt;element ref="{}noConfigMode" minOccurs="0"/>
 *         &lt;element ref="{}barBgColor" minOccurs="0"/>
 *         &lt;element ref="{}barFontColor" minOccurs="0"/>
 *         &lt;element ref="{}contentBgColor" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "column",
    "row",
    "notCloseable",
    "noEditMode",
    "noConfigMode",
    "barBgColor",
    "barFontColor",
    "contentBgColor"
})
@XmlRootElement(name = "portlet")
public class Portlet {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected BigInteger column;
    @XmlElement(required = true)
    protected BigInteger row;
    protected Boolean notCloseable;
    protected Boolean noEditMode;
    protected Boolean noConfigMode;
    protected String barBgColor;
    protected String barFontColor;
    protected String contentBgColor;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColumn(BigInteger value) {
        this.column = value;
    }

    /**
     * Gets the value of the row property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRow() {
        return row;
    }

    /**
     * Sets the value of the row property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRow(BigInteger value) {
        this.row = value;
    }

    /**
     * Gets the value of the notCloseable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNotCloseable() {
        return notCloseable;
    }

    /**
     * Sets the value of the notCloseable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNotCloseable(Boolean value) {
        this.notCloseable = value;
    }

    /**
     * Gets the value of the noEditMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoEditMode() {
        return noEditMode;
    }

    /**
     * Sets the value of the noEditMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoEditMode(Boolean value) {
        this.noEditMode = value;
    }

    /**
     * Gets the value of the noConfigMode property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoConfigMode() {
        return noConfigMode;
    }

    /**
     * Sets the value of the noConfigMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoConfigMode(Boolean value) {
        this.noConfigMode = value;
    }

    /**
     * Gets the value of the barBgColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarBgColor() {
        return barBgColor;
    }

    /**
     * Sets the value of the barBgColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarBgColor(String value) {
        this.barBgColor = value;
    }

    /**
     * Gets the value of the barFontColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBarFontColor() {
        return barFontColor;
    }

    /**
     * Sets the value of the barFontColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBarFontColor(String value) {
        this.barFontColor = value;
    }

    /**
     * Gets the value of the contentBgColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentBgColor() {
        return contentBgColor;
    }

    /**
     * Sets the value of the contentBgColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentBgColor(String value) {
        this.contentBgColor = value;
    }

}
